import type { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1710000000000 implements MigrationInterface {
  name = 'InitialSchema1710000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "pedidos" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "codigo_pedido" VARCHAR(100) NOT NULL,
        "nome_paciente" VARCHAR(255) NOT NULL,
        "data_nascimento" DATE NOT NULL,
        "sexo" VARCHAR(20) NOT NULL,
        "cod_unidade" VARCHAR(100) NOT NULL,
        "integrado" BOOLEAN NOT NULL DEFAULT FALSE,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_pedidos" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_pedidos_codigo_pedido" UNIQUE ("codigo_pedido"),
        CONSTRAINT "UQ_pedidos_id_codigo_pedido" UNIQUE ("id", "codigo_pedido")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "itens_pedido" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "pedido_id" BIGINT NOT NULL,
        "codigo_item_pedido" VARCHAR(100) NOT NULL,
        "accession_number" VARCHAR(100) NOT NULL,
        "modalidade" VARCHAR(50) NOT NULL,
        "nome_procedimento" VARCHAR(255) NOT NULL,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_itens_pedido" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_itens_pedido_pedido_codigo" UNIQUE ("pedido_id", "codigo_item_pedido"),
        CONSTRAINT "FK_itens_pedido_pedido" FOREIGN KEY ("pedido_id")
          REFERENCES "pedidos" ("id") ON DELETE RESTRICT
      )
    `);
    await queryRunner.query(
      'CREATE INDEX "IDX_itens_pedido_accession_number" ON "itens_pedido" ("accession_number")',
    );

    await queryRunner.query(`
      CREATE TABLE "exames" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "accession_number" VARCHAR(100) NOT NULL,
        "nome_paciente" VARCHAR(255) NOT NULL,
        "modalidade" VARCHAR(50) NOT NULL,
        "status" VARCHAR(50) NOT NULL,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_exames" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_exames_accession_number" UNIQUE ("accession_number")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "documentos" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "codigo_documento" VARCHAR(100) NOT NULL,
        "codigo_pedido_referencia" VARCHAR(100) NOT NULL,
        "pedido_id" BIGINT NULL,
        "nome_documento" VARCHAR(255) NOT NULL,
        "documento" TEXT NOT NULL,
        "integrado" BOOLEAN NOT NULL DEFAULT FALSE,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_documentos" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_documentos_codigo_pedido_codigo_documento"
          UNIQUE ("codigo_pedido_referencia", "codigo_documento"),
        CONSTRAINT "UQ_documentos_pedido_codigo_documento"
          UNIQUE ("pedido_id", "codigo_documento"),
        CONSTRAINT "FK_documentos_pedido_codigo"
          FOREIGN KEY ("pedido_id", "codigo_pedido_referencia")
          REFERENCES "pedidos" ("id", "codigo_pedido") ON DELETE RESTRICT
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "documentos_exames" (
        "documento_id" BIGINT NOT NULL,
        "exame_id" BIGINT NOT NULL,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_documentos_exames" PRIMARY KEY ("documento_id", "exame_id"),
        CONSTRAINT "FK_documentos_exames_documento" FOREIGN KEY ("documento_id")
          REFERENCES "documentos" ("id") ON DELETE RESTRICT,
        CONSTRAINT "FK_documentos_exames_exame" FOREIGN KEY ("exame_id")
          REFERENCES "exames" ("id") ON DELETE RESTRICT
      )
    `);
    await queryRunner.query(
      'CREATE INDEX "IDX_documentos_exames_exame_id" ON "documentos_exames" ("exame_id")',
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE "documentos_exames"');
    await queryRunner.query('DROP TABLE "documentos"');
    await queryRunner.query('DROP TABLE "exames"');
    await queryRunner.query('DROP TABLE "itens_pedido"');
    await queryRunner.query('DROP TABLE "pedidos"');
  }
}
